auth_enabled: false
server:
  http_listen_port: 3105
common:
  path_prefix: /tmp/loki
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  storage_config:
    boltdb_shipper:
      active_index_directory: /tmp/loki/boltdb-shipper-active
      shared_store: filesystem
    filesystem:
      directory: /tmp/loki/chunks
schema_config:
  configs:
    - from: 2020-10-27
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache
  filesystem:
    directory: /loki/chunks

limits_config:
  retention_period: 168h  # 7 дней
  allow_structured_metadata: false

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h  # 7 дней

query_scheduler:
  max_outstanding_requests_per_tenant: 2048

common:
  path_prefix: /tmp/loki